In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("data1/dandok.csv")
df

     CENTER_LONG  CENTER_LATI SGG_NM HOUSE_TYPE     PRICE_PER BJDONG_NM
0     127.036756    37.629044    강북구      단독다가구   1704.040732        번동
1     126.834321    37.526606    양천구      단독다가구   1397.574889       신월동
2     127.062592    37.480276    강남구      단독다가구   3942.294665       개포동
3     127.038549    37.500078    강남구      단독다가구   4637.912205       역삼동
4     126.944080    37.498708    동작구      단독다가구   3444.390270       상도동
..           ...          ...    ...        ...           ...       ...
314   127.008265    37.588721    성북구      단독다가구   2833.902313    동소문동2가
315   126.985284    37.578329    종로구      단독다가구  12601.331664        재동
316   126.971742    37.575314    종로구      단독다가구  15968.165117       내자동
317   127.019668    37.586498    성북구      단독다가구   2325.131309     보문동1가
318   126.964468    37.568548    종로구      단독다가구   4057.617200       교남동

[319 rows x 6 columns]

In [5]:
df = df.drop(df.index[21])

In [7]:
df = df.drop(df.index[235])

In [10]:
df = df.drop(df.index[37])

In [11]:
df = df.drop(df.index[38])

In [12]:
df

     CENTER_LONG  CENTER_LATI SGG_NM HOUSE_TYPE     PRICE_PER BJDONG_NM
0     127.036756    37.629044    강북구      단독다가구   1704.040732        번동
1     126.834321    37.526606    양천구      단독다가구   1397.574889       신월동
2     127.062592    37.480276    강남구      단독다가구   3942.294665       개포동
3     127.038549    37.500078    강남구      단독다가구   4637.912205       역삼동
4     126.944080    37.498708    동작구      단독다가구   3444.390270       상도동
..           ...          ...    ...        ...           ...       ...
314   127.008265    37.588721    성북구      단독다가구   2833.902313    동소문동2가
315   126.985284    37.578329    종로구      단독다가구  12601.331664        재동
316   126.971742    37.575314    종로구      단독다가구  15968.165117       내자동
317   127.019668    37.586498    성북구      단독다가구   2325.131309     보문동1가
318   126.964468    37.568548    종로구      단독다가구   4057.617200       교남동

[315 rows x 6 columns]

In [13]:
df = df.drop(df.index[32])

In [14]:
df = df.drop(df.index[35])

In [15]:
df

     CENTER_LONG  CENTER_LATI SGG_NM HOUSE_TYPE     PRICE_PER BJDONG_NM
0     127.036756    37.629044    강북구      단독다가구   1704.040732        번동
1     126.834321    37.526606    양천구      단독다가구   1397.574889       신월동
2     127.062592    37.480276    강남구      단독다가구   3942.294665       개포동
3     127.038549    37.500078    강남구      단독다가구   4637.912205       역삼동
4     126.944080    37.498708    동작구      단독다가구   3444.390270       상도동
..           ...          ...    ...        ...           ...       ...
314   127.008265    37.588721    성북구      단독다가구   2833.902313    동소문동2가
315   126.985284    37.578329    종로구      단독다가구  12601.331664        재동
316   126.971742    37.575314    종로구      단독다가구  15968.165117       내자동
317   127.019668    37.586498    성북구      단독다가구   2325.131309     보문동1가
318   126.964468    37.568548    종로구      단독다가구   4057.617200       교남동

[313 rows x 6 columns]

In [16]:
df.to_csv('data1/dandok_data.csv', index=False, encoding='utf-8')

In [17]:
df.index[38]

43